services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  app-1:
    image: nginx:alpine
    container_name: 'app-1'
    ports:
      - '8081:80'
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-1.rule=Host(`app-1.zrx.sh`)
      # - traefik.http.services.app-1.loadbalancer.server.port=8081

  app-2:
    image: nginx:alpine
    container_name: 'app-2'
    ports:
      - '8082:80'
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-2.rule=Host(`app-2.zrx.sh`)
      # - traefik.http.services.app-2.loadbalancer.server.port=8082

  # mhos:
  #   build: .
  #   container_name: 'mhos'
  #   ports:
  #     - '8888:8888'
  #   environment:
  #     - REDIS_DB=0
  #     - REDIS_ADDRESS=redis:6379
  #     - REDIS_PASSWORD=password
  #     - LOG_LEVEL=debug
  #     - PORT=8888
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
