name: Release

on:
  push:
    branches: ['main']

jobs:
  version:
    name: Get version
    uses: zareix/gh-actions/.github/workflows/get-version.yml@main
    with:
      type: regex
      file: main.go
      regex: 'const Version = "(\K[^"]+)'

  docker:
    name: Docker
    needs:
      - version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: zareix/gh-actions/.github/workflows/docker.yml@main
    with:
      tag: ${{ needs.version.outputs.version }}
      push-image: true
      platforms: linux/amd64,linux/arm64

  build:
    name: Build executable
    uses: ./.github/workflows/build.yml

  release:
    name: Create release
    needs:
      - version
      - docker
      - build
    permissions:
      contents: write
    uses: zareix/gh-actions/.github/workflows/release.yml@main
    with:
      tag: ${{ needs.version.outputs.version }}
      assets: traefik-mhos_build
